name: Build Bluesky Web

on:
  push:
    branches: [ dev ]

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Yarn dependencies
        run: yarn install

      - name: Start BlueSky Web App
        run: yarn start

      - name: Check if the client is running (example - adjust port if different)
        run: curl http://localhost:8081 || echo "Bluesky web client might not be running"
